name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
            env:
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
            #     - vol_name:/path/in/container
            #     - /path/to/container
            #     - /path/in/host:/path/in/container
            # options: --cpus 1
        steps:
            - name: Log node & OS version
              run: |
                node -v
                cat /etc/os-release
            - name: Log env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some text' > text.txt
            - name: Container in a step
              uses: docker://node:18.16-alpine3.17
              with:
                # entrypoint is not necessary here, since it is by default already the node command
                entrypoint: '/usr/local/bin/node'
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: Show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt
            - uses: actions/checkout@v3
            - name: Run a bash script
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: ./script.sh
                args: "foo bar baz"
            - name: This script doesnt have executable permissions
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: ./script2.sh
                args: "foo bar baz"
