name: Matrix
on: [push]

#------- ORIGINAL --------#
# {os: ubuntu-latest, node-version: 12, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 12, experimental: false}
# X {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 14}
# {os: ubuntu-latest, node-version: 18 }

jobs:
    node-matrix:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [12, 14, 16]
                include:
                  - os: ubuntu-latest
                    is-ubuntu: true
                  - os: macos-latest
                    node-version: 14
                  - experimental: false
                  - os: ubuntu-latest
                    node-version: 16
                    experimental: true
                  - os: ubuntu-latest
                    node-version: 18
                exclude:
                  - os: windows-latest
                    node-version: 14
            # if any job fails, other jobs will continue
            fail-fast: false
            # max-parallel: 3
        runs-on: ${{ matrix.os }}
        steps:
            - run: |
                node -v
                echo '${{ toJson(matrix) }}'
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v
