name: Workflow commands
on: [push]

jobs:
    testing-worfklow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
